### ISSUE TITLE
Replace all instances of `self` with `static`.

### ISSUE THREAD

**Issue by hailwood** [webfox/laravel-backed-enums#22]
In our traits we've got mixed `static::` and `self::` and `public function x(static $x)` and `public function y(self $y)`.

We should be consistent and replace all `self` references with `static`.

**Comment by vikas020807** [comment]
Hi there! I'm interested in working on this issue. Would it be possible to get assigned and contribute a fix?

**Comment by hailwood** [comment]
Hi @vikas020807 I've assigned this to you now if you're still interested :)
